apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-pzjq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/psturc_org/build-e2e-nfbq-tenant/test-app-qryd/devfile-sample-python-basic-pzjq@sha256:2a3ffb1437c834e0c373e2d2acdc0d87b249cc796c260e798432877e04bb0222
        name: my-python
        resources: {}
status: {}
